In [81]:
import tensorflow as tf
from gensim.models import word2vec
import gensim
import logging
import numpy as np

In [82]:
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)
sentences = word2vec.Text8Corpus("data/text8")

In [3]:
model = word2vec.Word2Vec(sentences, size=2, window=5, workers=5)

2016-10-09 22:58:29,247 : WARNING : consider setting layer size to a multiple of 4 for greater performance
2016-10-09 22:58:29,248 : INFO : collecting all words and their counts
2016-10-09 22:58:29,306 : INFO : PROGRESS: at sentence #0, processed 0 words, keeping 0 word types
2016-10-09 22:58:33,663 : INFO : collected 253855 word types from a corpus of 17005207 raw words and 1701 sentences
2016-10-09 22:58:33,999 : INFO : min_count=5 retains 71290 unique words (drops 182565)
2016-10-09 22:58:33,999 : INFO : min_count leaves 16718843 word corpus (98% of original 17005207)
2016-10-09 22:58:34,140 : INFO : deleting the raw counts dictionary of 253855 items
2016-10-09 22:58:34,153 : INFO : sample=0.001 downsamples 38 most-common words
2016-10-09 22:58:34,153 : INFO : downsampling leaves estimated 12506278 word corpus (74.8% of prior 16718843)
2016-10-09 22:58:34,154 : INFO : estimated required memory for 71290 words and 2 dimensions: 36785640 bytes
2016-10-09 22:58:34,349 : INFO : resettin

In [9]:
model['uk']

array([ 2.55509591,  1.26409554], dtype=float32)

In [29]:
model.save("models/word2vec_2D.model")


NameError: name 'model' is not defined

In [83]:
word_model = gensim.models.Word2Vec.load("models/word2vec_2D.model")

2016-10-11 20:59:25,134 : INFO : loading Word2Vec object from models/word2vec_2D.model
2016-10-11 20:59:25,359 : INFO : setting ignored attribute syn0norm to None
2016-10-11 20:59:25,364 : INFO : setting ignored attribute cum_table to None


In [96]:
matrix = np.zeros(shape=[len(word_model.vocab), 2])
id2word = dict()
word2id = dict()

In [97]:
for i,k in enumerate(word_model.vocab.keys()):
    id2word[i] = k
    word2id[k] = i
    matrix[i] = word_model[k]

In [100]:
embedding_matrix = tf.constant(matrix)

In [101]:
emd = tf.nn.embedding_lookup(embedding_matrix, 1)

In [102]:
with tf.Session() as sess:
    em = sess.run(emd)
    

In [103]:
em

array([ 0.73015785,  1.44113648])

In [104]:
import pickle 


In [105]:
with open("embedding_matrix_2D", 'wb') as f:
    pickle.dump([matrix, id2word, word2id], f)

In [106]:
x, y, z = pickle.load(open("embedding_matrix_2D", 'rb'))

array([[ 0.16928734,  0.56346083],
       [ 0.73015785,  1.44113648],
       [ 0.25020877,  0.45025212],
       ..., 
       [ 3.04497743,  1.08371174],
       [ 0.45141   ,  0.76665598],
       [-0.18308809,  0.90003824]])